x-common-variables: &common-variables
  ASPNETCORE_ENVIRONMENT: Development
  rabbitMQ__username: guest
  rabbitMQ__password: guest
  rabbitMQ__host: rabbitmq
  rabbitMQ__virtualHost: /
  JWT__Issuer: https://deck-manager.local.com
  JWT__Audience: https://deck-manager.local.com
  # To generate JWT__SecretKey run openssl rand -base64 64
  JWT__SecretKey: lqgruqLbLX79KEyCAbGt3Y+kAcT5DfE8zTgqxRb1e7E8Bzw6OnSBZbJ6XAsBNBRv1v0LIVVjDq+D5LQh2ABOCg==
  auth__MaxLoginAttempts: 5
  ApiBaseUrl: http://localhost:8080/
  UserService__BaseAddress: http://users-api:8080

services:
  # User Nginx as api gateway
  api-gateway:
    build:
      context: nginx-api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - dm-network
    restart: always
    depends_on:
      - users-api
      - auth-api
      # - decks-api
      # - cards-api
      # - games-api

  users-api:
    build:
      context: services/users
      dockerfile: WebApi/Dockerfile
    environment:
      <<: *common-variables
    ports:
      - 5000:8080
    networks:
      - dm-network
    depends_on:
      - rabbitmq
    restart: always

  auth-api:
    build:
      context: services/auth
      dockerfile: WebApi/Dockerfile
    environment:
      <<: *common-variables
    ports:
      - 5001:8080
    networks:
      - dm-network
    depends_on:
      - rabbitmq
    restart: always
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - dm-network
    restart: always
  
networks:
  dm-network:
    driver: bridge