// <auto-generated />
using System;
using Api.Features;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsoleApp.Migrations
{
    [DbContext(typeof(SubscribersDbContext))]
    partial class SubscribersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Features.Subscriber.Models.Subscriber", b =>
                {
                    b.Property<Guid>("SubscriberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("SubscribedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscribed_on");

                    b.HasKey("SubscriberID")
                        .HasName("pk_subscribers");

                    b.ToTable("subscribers", (string)null);
                });

            modelBuilder.Entity("Api.Features.Subscriber.Sagas.NewsletterOnboardingSagaData", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_state");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("FollowUpEmailSent")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_up_email_sent");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<Guid>("SubscriberID")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<bool>("WelcomeEmailSent")
                        .HasColumnType("boolean")
                        .HasColumnName("welcome_email_sent");

                    b.HasKey("CorrelationId")
                        .HasName("pk_newsletter_onboarding_saga_datas");

                    b.ToTable("newsletter_onboarding_saga_datas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
